In [3]:
my_lst = [1,2,3]

In [5]:
my_lst

[1, 2, 3]

In [6]:
import numpy as np


In [8]:
arr = np.array(my_lst)

In [9]:
arr

array([1, 2, 3])

In [16]:
my_lst = [[1,7,8],[2,10,11],[3,4,5]]

In [17]:
arr = np.array(my_lst)

In [19]:
print (arr)

[[ 1  7  8]
 [ 2 10 11]
 [ 3  4  5]]


In [3]:
import numpy as np

In [4]:
np.random.randn(5)

array([ 0.054873  ,  1.26917104,  1.42405065, -0.47785969, -0.43511714])